### ISSUE TITLE
Good results and performances?

### ISSUE THREAD

**Issue by romainreignier** [phonophob/STM32F1xx-ILI9341#1]
Hello,
Thanks for sharing your work on that display driver with stm32f1.
I have tried it on a stm32f103c8t6 board and finally managed to get something on the screen, but I had to modified a couple of lines to make the project compile. And then, I have noticed that the result on the screen is not what we would expect (missing text, additional lines...) and I had to wait several seconds to get the display showing the content of `Display_Init(void)` function.
So I was wondering if you have noticed the same kind of issues because it is an early attempt to get the display working with the HAL library. Or if it is me that have missed a point.
Thanks,
Romain

**Comment by vpatoka** [comment]
I saw that slowness at the begin. Basically SPI bus speed could be faster:
Here is Init from my another project which works better 

/**
- @brief  Power on the LCD.
- @param  None
- @retval None
  _/
  void ili9341_Init(void)
  {
  /_ Initialize ILI9341 low level bus layer ----------------------------------*/
  ili9341_IO_Init();
  
  /\* Default value for draw propriety */
  DrawProp.BackColor = 0x0000;
  DrawProp.pFont     = &Font12;
  //    DrawProp.pFont     = &FontVFDa;
  DrawProp.TextColor = 0xFFFF;;
  
  ili9341_WriteReg(0xEF);
  ili9341_WriteData(0x03);
  ili9341_WriteData(0x80);
  ili9341_WriteData(0x02);
  
  ili9341_WriteReg(0xCF);  
  ili9341_WriteData(0x00); 
  ili9341_WriteData(0XC1); 
  ili9341_WriteData(0X30); 
  
  ili9341_WriteReg(0xED);  
  ili9341_WriteData(0x64); 
  ili9341_WriteData(0x03); 
  ili9341_WriteData(0X12); 
  ili9341_WriteData(0X81); 
  
  ili9341_WriteReg(0xE8);  
  ili9341_WriteData(0x85); 
  ili9341_WriteData(0x00); 
  ili9341_WriteData(0x78); 
  
  ili9341_WriteReg(0xCB);  
  ili9341_WriteData(0x39); 
  ili9341_WriteData(0x2C); 
  ili9341_WriteData(0x00); 
  ili9341_WriteData(0x34); 
  ili9341_WriteData(0x02); 
  
  ili9341_WriteReg(0xF7);  
  ili9341_WriteData(0x20); 
  
  ili9341_WriteReg(0xEA);  
  ili9341_WriteData(0x00); 
  ili9341_WriteData(0x00); 
  
  ili9341_WriteReg(LCD_POWER1);    //Power control 
  ili9341_WriteData(0x23);   //VRH[5:0] 
  
  ili9341_WriteReg(LCD_POWER1);    //Power control 
  ili9341_WriteData(0x10);   //SAP[2:0];BT[3:0] 
  
  ili9341_WriteReg(LCD_VCOM1);    //VCM control 
  ili9341_WriteData(0x3e); //¶Ô±È¶Èµ÷½Ú
  ili9341_WriteData(0x28); 
  
  ili9341_WriteReg(LCD_VCOM2);    //VCM control2 
  ili9341_WriteData(0x86);  //--
  
  ili9341_WriteReg(LCD_MAC);    // Memory Access Control 
  ili9341_WriteData(0x48);
  
  ili9341_WriteReg(LCD_PIXEL_FORMAT);  
  ili9341_WriteData(0x55); 
  
  ili9341_WriteReg(LCD_FRMCTR1);  
  ili9341_WriteData(0x00);  
  ili9341_WriteData(0x18); 
  
  ili9341_WriteReg(LCD_DFC);    // Display Function Control 
  ili9341_WriteData(0x08); 
  ili9341_WriteData(0x82);
  ili9341_WriteData(0x27);  
  
  ili9341_WriteReg(0xF2);    // 3Gamma Function Disable 
  ili9341_WriteData(0x00); 
  
  ili9341_WriteReg(LCD_GAMMA);    //Gamma curve selected 
  ili9341_WriteData(0x01); 
  
  ili9341_WriteReg(LCD_PGAMMA);    //Set Gamma 
  ili9341_WriteData(0x0F); 
  ili9341_WriteData(0x31); 
  ili9341_WriteData(0x2B); 
  ili9341_WriteData(0x0C); 
  ili9341_WriteData(0x0E); 
  ili9341_WriteData(0x08); 
  ili9341_WriteData(0x4E); 
  ili9341_WriteData(0xF1); 
  ili9341_WriteData(0x37); 
  ili9341_WriteData(0x07); 
  ili9341_WriteData(0x10); 
  ili9341_WriteData(0x03); 
  ili9341_WriteData(0x0E); 
  ili9341_WriteData(0x09); 
  ili9341_WriteData(0x00); 
  
  ili9341_WriteReg(LCD_NGAMMA);    //Set Gamma 
  ili9341_WriteData(0x00); 
  ili9341_WriteData(0x0E); 
  ili9341_WriteData(0x14); 
  ili9341_WriteData(0x03); 
  ili9341_WriteData(0x11); 
  ili9341_WriteData(0x07); 
  ili9341_WriteData(0x31); 
  ili9341_WriteData(0xC1); 
  ili9341_WriteData(0x48); 
  ili9341_WriteData(0x08); 
  ili9341_WriteData(0x0F); 
  ili9341_WriteData(0x0C); 
  ili9341_WriteData(0x31); 
  ili9341_WriteData(0x36); 
  ili9341_WriteData(0x0F); 
  
  ili9341_Landscape();
  
  ili9341_WriteReg(LCD_SLEEP_OUT);    //Exit Sleep 
  ili9341_Delay(200);  
  ili9341_WriteReg(LCD_DISPLAY_ON);    //Display on 

}    

/**
- @brief  Configures the LCD_SPI interface.
- @retval None
  */
  void ili9341_IO_Init(void)
  {
  
  // HW Reset for LCD
  LCD_RST_LOW();
  ili9341_Delay(200);
  LCD_RST_HIGH();
  
  // Set or Reset the control line 
  LCD_CS_LOW();
  LCD_CS_HIGH();
  
  hspi1.Instance = LCD_SPIx;
  hspi1.Init.Mode = SPI_MODE_MASTER;
  hspi1.Init.Direction = SPI_DIRECTION_2LINES;
  hspi1.Init.DataSize = SPI_DATASIZE_8BIT;
  hspi1.Init.CLKPolarity = SPI_POLARITY_LOW;
  hspi1.Init.CLKPhase = SPI_PHASE_1EDGE;
  hspi1.Init.NSS = SPI_NSS_SOFT;
  hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_16;    // Only 64 works for some uncertain reason | 16
  hspi1.Init.FirstBit = SPI_FIRSTBIT_MSB;
  hspi1.Init.TIMode = SPI_TIMODE_DISABLED;
  hspi1.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLED;
  hspi1.Init.CRCPolynomial = 10;
  HAL_SPI_Init(&hspi1);
  
  if(HAL_SPI_Init(&hspi1) != HAL_OK) {
      /\* Initialization Error */
      ili9341_Error();
  }
  
  while (HAL_SPI_GetState(&hspi1) != HAL_SPI_STATE_READY);
  
  ili9341_LED(1);

}

**Comment by romainreignier** [comment]
Thank you for your feedback, I will try this.
